# Generated by Django 4.2.5 on 2023-09-07 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('singers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(blank=True, max_length=255, verbose_name='Название Альбома')),
                ('release_year', models.IntegerField(verbose_name='Дата Выпуска')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singers.executor')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
    ]
